---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-app
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
