---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-app
  labels:
    app: app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
